import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " Next Js Basic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* nav start */}
        <Navbar></Navbar>
       
        <div className="">
        {children}
        </div>
        {/* footer start */}
        <footer className="bg-blue-600">
          This is footer section
        </footer>
        {/* footer end */}
      </body>
    </html>
  );
}
