import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " Next Js Basic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* nav start */}
        <nav>
          <h4>Logo</h4>
          <ul>
            <li>About</li>
            <li>Services</li>
            <li>Contact</li>
          </ul>
        </nav>
        {/* nav end */}
        <div className="h-screen">
        {children}
        </div>
        {/* footer start */}
        <footer>
          This is footer section
        </footer>
        {/* footer end */}
      </body>
    </html>
  );
}
